services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - project-management-net
  server:
    build: ./server
    container_name: server
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - project-management-net

  postgres:
    image: postgis/postgis:17-3.5
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: naku
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-management-net

networks:
  project-management-net:
    driver: bridge

volumes:
  postgres_data:
    external: true
